# Generated by Django 5.1.4 on 2024-12-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagerapi', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=6),
        ),
    ]
