# Generated by Django 5.1.4 on 2024-12-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagerapi', '0007_task_duedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='dueDate',
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
